name: Deploy to Hugging Face Space

on:
  # push:
  #   branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

env:
  HF_USERNAME: rassulya
  HF_SPACE: test_cicd
  HF_REPO_URL: https://huggingface.co/spaces/rassulya/test_cicd

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "Rassulya"
          git config --global user.email "rasul.yermagambet@gmail.com"

      - name: Clone Hugging Face Space repo
        run: |
          git clone https://huggingface.co/spaces/${{ env.HF_USERNAME }}/${{ env.HF_SPACE }} hf-space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Copy files to Space repo
        run: |
          rsync -av --delete --exclude=".git" ./ hf-space/
          cd hf-space
          git add .
          git commit -m "🚀 Auto-deploy from source repo [skip ci]" || echo "No changes to commit"
          git push https://${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ env.HF_USERNAME }}/${{ env.HF_SPACE }} HEAD:main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
