name: Deploy to Hugging Face Space

on:
  pull_request:
    branches: [main]
    types: [closed]

env:
  HF_USERNAME: rassulya
  HF_SPACE: test_cicd

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config --global user.name "Rassulya"
          git config --global user.email "rasul.yermagambet@gmail.com"

      - name: Clone Hugging Face Space repo
        run: |
          git clone https://huggingface.co/spaces/${{ env.HF_USERNAME }}/${{ env.HF_SPACE }} ../hf-space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Copy files to Space repo
        run: |
          rsync -av --delete --exclude=".git" ./ ../hf-space/ || true
          cd ../hf-space
          git add .
          git commit -m "🚀 Auto-deploy from PR merge [skip ci]" || echo "No changes to commit"
          git push https://${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ env.HF_USERNAME }}/${{ env.HF_SPACE }} HEAD:main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
